ersion: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: achatdb

  achat-backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8083:8083
    volumes:
      - ./m2:/root/.m2
    stdin_open: true
    tty: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

volumes:
  db:
