version: '3.8'
services:
  achat_back:
    image: alaaeddinezarrouk/achat:1.0
    ports:
      - "80:80"
  sql_database:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root